name: Jenkins Simlation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Jenkinsfile
        uses: jenkinsci/jenkinsfile-runner-github-actions@main
        with:
          jenkinsfile: Jenkinsfile

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Test with Gradle
        run: ./gradlew test
